version: '2.1'
services:
  backend:
    build: ./
    container_name: web-auction-backend
    volumes:
      - ./:/usr/src/app
    ports:
      - '3002:3002'
    environment:
      NODE_ENV: production
      PORT: 3002
  frontend:
    build: ./src/client
    container_name: web-auction-frontend
    ports:
      - '3001:80'
    environment:
      NODE_ENV: production

